### ISSUE TITLE
Explota el modulo en magento 1.9.2.2

### ISSUE THREAD

**Issue by pixlKing** [ecloudsolutions/andreani#3]
Al instalar...

```
Error in file: "C:\wamp\www\example\src\app\code\community\Ecloud\Andreani\sql\andreani_setup\mysql4-install-0.1.1.php" - Notice: Undefined offset: 0  in C:\wamp\www\example\src\app\code\core\Mage\Core\Model\App.php on line 981

#0 C:\wamp\www\example\src\app\code\core\Mage\Core\Model\Resource\Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 C:\wamp\www\example\src\app\code\core\Mage\Core\Model\Resource\Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '0.1.12')
#2 C:\wamp\www\example\src\app\code\core\Mage\Core\Model\Resource\Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('0.1.12')
#3 C:\wamp\www\example\src\app\code\core\Mage\Core\Model\Resource\Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 C:\wamp\www\example\src\app\code\core\Mage\Core\Model\App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 C:\wamp\www\example\src\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Model_App->_initModules()
#6 C:\wamp\www\example\src\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#7 C:\wamp\www\example\src\index.php(83): Mage::run('', 'store')
#8 {main}
```

**Comment by pixlKing** [comment]
El error pareciera estar en esta linea: https://github.com/ecloudsolutions/andreani/blob/master/app/code/community/Ecloud/Andreani/sql/andreani_setup/mysql4-install-0.1.1.php#L26 en la cual se llama a `Mage::app()->getStore(Mage_Core_Model_App::ADMIN_STORE_ID)` para obtener la tienda base, pero internamente Magento detecta que está en Update Mode y devuelve una tienda default que no es realmente la tienda admin.

Para arreglar este problema, se debe reemplazar esa linea por `$store = Mage::getModel('core/store')->load(Mage_Core_Model_App::ADMIN_STORE_ID);`
